export const items = [
	'Fail to check traffic conditions',
	'Roll backwards',
	'Stop in improper position',
	'Fail to check traffic conditions',
	'Start jerkily',
	'Roll backwards',
	'Fail to check traffic conditions',
	'Roll backwards / forwards',
	'Fail to return steering lock before stopping',
	'Turn steering while vehicle is at rest',
	'Strike object',
	'( ) point-turn',
	'Fail to check traffic conditions',
	'Roll backwards forwards',
	'Park in improper position',
	'Strike object',
	'Wrong positioning on turns',
	'Low speed / slow reaction when making an emergency stop',
	'Inadequate control when making an emergency stop',
	'Inadequate precaution',
	'Fail to check traffic conditions',
	'Roll backwards / forwards',
	'Fail to check traffic conditions',
	'Roll backwards forwards',
	'Stop in improper position',
	'Fail to switch Off engine and or engage gear before quitting vehicle',
	'Fail to check traffic conditions before changing lanes',
	'Wrong side driving',
	'Cut out sharply from behind object',
	'Cut in sharply in front of object',
	'Drive too close to object',
	'Fail to keep in proper lane',
	'Fail to act on signals from other vehicles',
	'Inconsiderate to other road users',
	'Drive in excess of speed limit',
	'Fail to adjust speed to suit traffic conditions',
	'Give improper signal',
	'Fail to signal in good time',
	'Omit signal',
	'Cause examiner to take action',
	'Strike object',
	"Free wheeling in 'neutral'",
	'Noisy gear changing',
	'Fail to use suitable gears',
	'Fail to engage gear',
	'Fail to use handbrake',
	'Lack alertness and anticipation',
	'Fail to make full use of mirrors',
	'Lose balance ( For Motor Cycle only )',
	'Fail to double declutch when changing gears ( For Commercial Vehicle Only )',
	'Improper use of handbrake',
	'Improper control of footbrake',
	'Improper control of accelerator',
	'Improper control of clutch',
	'Improper control of steering',
	'Fail to check traffic conditions',
	'Overtake in unfavourable conditions',
	'Fail to check traffic conditions',
	'Wrong positioning on turns',
	'Fail to yield right of way',
	'Fail to take right of way',
	'Fail to act on Regulatory Signs / Road Markings',
	'Fail to act on Warning Informatory Signs or Road Markings',
	'Fail to act on Duty point Signals',
	'Fail to act on Traffic Lights',
	'Fail to stop for pedestrian using ZEBRA CROSSING',
	'Lose balance When negotiating figure "8"',
	'Strike object when negotiating figure "8"',
	'Fail to control machine at walking pace',
	'Fail to comply with Gear Changing Exercise as instructed',
	'Improper uncoupling procedures',
	'Improper recoupling procedures',
	'Safety precautions'
];
export const serious = [
	11, 12, 16, 19, 27, 28, 29, 30, 35, 40, 41, 42, 49, 56, 57, 62, 64, 66, 67, 68
]
export const category: {[key: number]: string} = {
	1: "STOP ON SLOPE\n( Not Applicable To Motor Cycle part B Test )",
	4: "START ON SLOPE\n( Not Applicable To Motor Cycle Part B Test )",
	7: "TURNABOUT IN A NARROW ROAD\n( Not Applicable To Motor Cycle And Articulated Vehicle )",
	13: "REVERSING AND PARKING\n( Not Applicable To Motor Cycle )",
	17: "MANOEUVRES FOR MOTOR CYCLE PART B TEST",
	20: "STARTING",
	21: "MOVING OFF",
	23: "STOPPING",
	27: "DRIVING CONCEPT",
	35: "SPEED CONTROL",
	37: "USE OF SIGNAL",
	40: "DRIVING TECHNIQUE",
	51: "USE OF CONTROL",
	56: "OVERTAKING",
	58: "ROAD JUNCTION",
	62: "TRAFFIC SIGNS ROAD MARKINGS",
	64: "TRAFFIC SIGNALS",
	66: "PEDESTRIAN CROSSING",
	67: "MANOEUVRES FOR MOTOR CYCLE",
	70: "MANOEUVRES FOR ARTICULATED VEHICLE",
	73: "ORAL TEST"
}
